[package]
name = "etclient-core"
version = "0.1.0"
license = "Apache-2.0"
description = "Core functionality for etclient."
authors = ["Wei Tang <hi@that.world>"]
repository = "https://github.com/ethereumproject/etclient"

[dependencies]
